[package]
name = "inversor"
version = "0.1.0"
authors = ["Eugenia Franchi <mfranchi@fi.uba.ar>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"